### ISSUE TITLE
Bluetooth at 3MBps 

### ISSUE THREAD

**Issue by fboudra** [96boards/bugs#3]
_From @usmanahmad-linaro on February 17, 2015 7:59_

Bluetooth at 3MBps is currently not supported on the board.

_Copied from original issue: 96boards/linux#3_

**Comment by fboudra** [comment]
_From @ldts on February 17, 2015 14:30_

Diagnosis: after the bluetooth stack receives the acknowledge from the firmware that is ok to increase the baudrate, the UIM set the termios of amba-pl011.c to 3mbps. At that poing the high speed UART seems to stop responding and communication with the BT firmware is lost.

**Comment by sbambrough** [comment]
The issue is that the kernel's BT stack can not communicate with the BT device when the UART is set at speeds over 115K (device tree setting). Since the linux kernel can't retrieve the BT device firmware version, the BT stack fails early before UIM can try to switch the BT device to the speed
reported by KIM on sysfs.

So I believe the problem lies with the amba-pl011.c uart (not the BT device or BT stack)
Jorge

**Comment by ldts** [comment]
unit test:
-----------

1. download and install a recent HiKey release 
https://builds.96boards.org/snapshots/hikey/debian

2.prepare the kernel for debugging and modify the UART input clock
    1. enable the BT debug info (define #DEBUG macro in drivers/misc/ti-st/*.c)
    2. enable hci debug info (net/bluetooth/hci-core.c)
    3. modify the DT clock setting for uart@f7111000  - use the 150MHz clock instead

3. on boot, the BT stack will have failed to synch up with the device

To attempt a new synchup  (to capture new traces)
$ service ti-uim stop
$ modprobe -r btwilink

Now re-load the btwilink module which will attempt to retrieve the BT firmware version and will eventually timeout (no need to start the ti-uim service)
$ modprobe btwilink

**Comment by ldts** [comment]
96boards/linux#20

**Comment by sbambrough** [comment]
I can't tell if this was fixed.  You keep referring to other issues.
Following the chain is making me dizzy.
You need better comments, particularly when you close and issue.  How was
it resolved.
Please fix it up.

Scott

On Thu, Mar 12, 2015 at 1:58 PM, Jorge A. Ramirez-Ortiz <
notifications@github.com> wrote:

> Closed #3 <https://github.com/96boards/bugs/issues/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/96boards/bugs/issues/3#event-251107873>.
>



-- 
Scott Bambrough
Technical Director, Member Services
Linaro <http://www.linaro.org>

**Comment by ldts** [comment]
No, it hasnt been fixed: we know the root cause of the issue (high speed clock settings) and how to fix it. We rejected the first proposal due to violation of some basic software principles (clock consumer in the UART needing to be aware of the clock hierarchy). Once that this is addressed and the fix delivered you will know - software commits will be associated to issues#

All it is happening with this report is that the issue itself is being transferred to the linux/issues repository. I'd like to differentiate tracking of product issues from the tracking of kernel issues as well as allow the association mentioned above.
