### ISSUE TITLE
Display incorrect on X Windows

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#37]
Using snapshot 251
Looking at the bar at the bottom of the display, the off button is split, part of it displays on the far left, part on the far right.   Looks like the display is wrapped.

**Comment by sbambrough** [comment]
Suspect the wrap issue in #2 isn't fixed, just looks like it in Android.

**Comment by docularxu** [comment]
This bug is fixed with commit: c87bedf
 I verified with my monitor.
Build 253 should have included this commit.
https://builds.96boards.org/snapshots/hikey/debian/253

**Comment by docularxu** [comment]
This is fixed in https://builds.96boards.org/snapshots/hikey/debian/254. 

Scott, would you like to double check this on your settings? In my TV (using an HDMI-Display Port converter, then connected to my Dell U2412M) I can see the X window and Android UI not wrapped. I am wondering could it be different on your HDMI monitor and the display wraps? If yes, then we need to check it. If not, please close this issue.

**Comment by sbambrough** [comment]
Verified fixed in snapshot 260.

**Comment by sbambrough** [comment]
Verified as fixed in snapshot 260.

On Mon, Apr 13, 2015 at 8:40 PM, Guodong Xu <notifications@github.com>
wrote:

> This is fixed in https://builds.96boards.org/snapshots/hikey/debian/254.
>
> Scott, would you like to double check this on your settings? In my TV
> (using an HDMI-Display Port converter, then connected to my Dell U2412M) I
> can see the X window and Android UI not wrapped. I am wondering could it be
> different on your HDMI monitor and the display wraps? If yes, then we need
> to check it. If not, please close this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/96boards/bugs/issues/37#issuecomment-92547038>.
>



-- 
Scott Bambrough
Technical Director, Member Services
Linaro <http://www.linaro.org>
