### ISSUE TITLE
HiKey - Debian X - in 15 minutes, do nothing, then system will hang.

### ISSUE THREAD

**Issue by docularxu** [96boards/bugs#41]
Using one of the snapshot Debian ALIP build, boot up the board. After the Debian destop is shown on HDMI monitor, leave the board there for about 15 minutes and do nothing (don't touch USB keyboard or mouse), then system will hang.

This is 100% reproducible. When system hangs, there is:
1. no any log output in serail port. Even I have run 'echo 8 > /proc/sys/kernel/printk' in advance.
2. the heart-beat LED stops blinking. It will be either in On or Off, depending on its final status when system hangs.
3. HDMI display goes into black.

**Comment by docularxu** [comment]
Note: I cannot reproduce this issue in Debian developer build, where HDMI monitor is used to show the console, and it can always be 'waken up' from the 15 mintues timeout by a key-press in USB keyboard.

**Comment by docularxu** [comment]
Verified on debian snapshot build 254 (https://builds.96boards.org/snapshots/hikey/debian/254),

Issue still exists. After 10 minutes with no action on USB keyboard and USB mouse, the HDMI display goes blank, and on serial console, there is no any output, and system hangs.

Touching the SoC chip, it is very hot, burning high. Suspect the board shuts down because of thermal reasons. 

Next: What's the reason of making CPU keep burning?

**Comment by Leo-Yan** [comment]
Suppose this is caused by tty which will has 10 miutes' timout, and it will to turn off hdmi; can we check what's the call back function for hdmi's tty off?

leoy@leoy-linaro:~/Work/hisi/linux$ git diff
diff --git a/drivers/tty/vt/vt.c b/drivers/tty/vt/vt.c
index b33b00b..3d36166 100644
--- a/drivers/tty/vt/vt.c
+++ b/drivers/tty/vt/vt.c
@@ -176,7 +176,7 @@ int console_blanked;
 
 static int vesa_blank_mode; /* 0:none 1:suspendV 2:suspendH 3:powerdown */
 static int vesa_off_interval;
-static int blankinterval = 10*60;
+static int blankinterval = 0;
 core_param(consoleblank, blankinterval, int, 0444);
 
 static DECLARE_WORK(console_work, console_callback);

**Comment by Leo-Yan** [comment]
After apply below patch, then then hang issue will dismiss; so this hang is caused by turn off display by windows manager and hdmi's driver will disable clock according to the request. Need Xinliang help check this issue.

diff --git a/drivers/gpu/drm/hisilicon/hisi_drm_ade.c b/drivers/gpu/drm/hisilicon/hisi_drm_ade.c
index cb473b0..955b978 100644
--- a/drivers/gpu/drm/hisilicon/hisi_drm_ade.c
+++ b/drivers/gpu/drm/hisilicon/hisi_drm_ade.c
@@ -295,8 +295,8 @@ static void hisi_drm_crtc_dpms(struct drm_crtc *crtc, int mode)
 
        if (mode == DRM_MODE_DPMS_ON)
                hisi_drm_crtc_ade_enable(crtc_ade);
-       else
-               hisi_drm_crtc_ade_disable(crtc_ade);
+       //else
+       //      hisi_drm_crtc_ade_disable(crtc_ade);
 
        crtc_ade->dpms = mode;
        DRM_DEBUG_DRIVER("crtc_dpms exit successfully.\n");
diff --git a/drivers/gpu/drm/hisilicon/hisi_drm_drv.c b/drivers/gpu/drm/hisilicon/hisi_drm_drv.c
index d2e4098..9efb299 100644
--- a/drivers/gpu/drm/hisilicon/hisi_drm_drv.c
+++ b/drivers/gpu/drm/hisilicon/hisi_drm_drv.c
@@ -98,8 +98,8 @@ static int hisi_drm_load(struct drm_device *drm_dev, unsigned long flags)
        int ret;
        struct hisi_drm_private *private;
 
-       /* debug setting
-       drm_debug = DRM_UT_DRIVER|DRM_UT_KMS|DRM_UT_CORE|DRM_UT_PRIME; */
+       /* debug setting */
+       drm_debug = DRM_UT_DRIVER|DRM_UT_KMS|DRM_UT_CORE|DRM_UT_PRIME;
        DRM_DEBUG_DRIVER("enter.\n");
 
        private = kzalloc(sizeof(struct hisi_drm_private), GFP_KERNEL);
diff --git a/drivers/gpu/drm/hisilicon/hisi_drm_dsi.c b/drivers/gpu/drm/hisilicon/hisi_drm_dsi.c
index b493813..c84da24 100644
--- a/drivers/gpu/drm/hisilicon/hisi_drm_dsi.c
+++ b/drivers/gpu/drm/hisilicon/hisi_drm_dsi.c
@@ -706,7 +706,7 @@ static void hisi_drm_encoder_dpms(struct drm_encoder *encoder, int mode)
                hisi_dsi_enable(dsi);
                break;
        default:
-               hisi_dsi_disable(dsi);
+               //hisi_dsi_disable(dsi);
                break;
        }

**Comment by docularxu** [comment]
Root caused by Leo Yan. Need Xinliang to make an official fix. 

Workaround exists: by disabling X window sleep.

**Comment by Leo-Yan** [comment]
Pls check the PR: https://github.com/96boards/linux/pull/47, which can fix this issue.

**Comment by sbambrough** [comment]
Screen stays on if you go into LXTerminal window and issue the commands:
$ xset s off
$ xset -dpms

This can be done automatically by appending the following lines to ~/.config/lxsession/LXDE/autostart
@xset s off
@xset -dpms

This could potentially be the backup position if https://github.com/96boards/linux/pull/47 does not fix the problem.

**Comment by xin3liang** [comment]
please check [pull request 51](https://github.com/96boards/linux/pull/51). which base on [pull request 47](https://github.com/96boards/linux/pull/47) and fix this issue. Have tested both development and alip debian imgs.

**Comment by sbambrough** [comment]
Tested on snapshot 272.  Fixed.
