### ISSUE TITLE
Debian: Rootfs: fsck: error 2 (No such file or directory)

### ISSUE THREAD

**Issue by Leo-Yan** [96boards/bugs#60]
Every time when boot up Debian's root fs, it will report below log:
"fsck: error 2 (No such file or directory) while executing fsck.ext4 for /dev/mmcblk0p9; fsck exited with status code 8"

**Comment by Leo-Yan** [comment]
@fboudra  i checked the ramdisk.img, in the ramdisk image, it only has fsck but have not fsck.ext4, so that when fsck to find fsck.ext4, it will report this failure.  Could u check why the ramdisk image in https://builds.96boards.org/snapshots/hikey/debian/274/boot-fat.emmc.img.gz have not included fsck.ext4 (or e2fsck).

**Comment by fboudra** [comment]
I can confirm the generated initrd is missing sbin/e2fsck binary (fsck.ext4 is a symlink).
Running "update-initramfs -u -t" will re-generate an initramfs with the binary included.

e2fsprogs should be installed before initramfs-tools in order to include fsck.ext4.
The initd is generated by update-initramfs during linaro-media-create step.

**Comment by suihkulokki** [comment]
e2fsprogs is already part of developer/alip images. It seems the error is rather that l-m-c runs update-initramfs before it generates the etc/fstab, so update-initramfs doesn't know that rootfs is ext4 and needs fsck.ext4.

**Comment by fboudra** [comment]
fixed in build > 291
