### ISSUE TITLE
Bluetooth no longer powers on automatically...

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#79]
BT used to power on automatically.

There is a udev rule for this:
```
root@linaro-alip:~# cat /lib/udev/rules.d/50-bluetooth-hci-auto-poweron.rules
# Set bluetooth power up
ACTION=="add", SUBSYSTEM=="bluetooth", KERNEL=="hci[0-9]*", RUN+="/bin/hciconfig %k up"
```
One problem is bluetooth seems to be soft blocked at startup.  Immediately after booting I get:
```
root@linaro-alip:~# rfkill list bluetooth
1: hci0: Bluetooth
	Soft blocked: yes
	Hard blocked: no
```
This will prevent the udev rule from working.

**Comment by docularxu** [comment]
1. No such issue in hikey debian developer image. Bluetooth powers on automatically, and there is no 'soft blocked', and you can do whatever you want through hciconfig/ hcitool.

2. In hikey debian ALIP image, somehow, I think this is expected behavior: 
"Soft blocked: yes ", that is enforced by the alip app Blueman "Bluetooth Manager". 
It takes the lock to avoid 'mistakenly' turning up bt in the command line. such as 'hciconfig hci0 up'
You can turn on bluetooth through right-clicking the bluetooth taskbar icon and choosing  'Turn Bluetooth On'. Actually, once you did that, 'rfkill list' will show 'Soft blocked: no'.

I think we should close this bug with no modification required.

Comments? Can we set the 'Bluetooth Manager' to turn on BT by default?

**Comment by fboudra** [comment]
re-assign to me. I think it's a user space issue.

**Comment by sbambrough** [comment]
Tested in snapshot 287, with new partition table and alip image.
Booted, blueman-applet runs & shows bluetooth off, rfkill shows hci0 is soft blocked.

Moved /etc/xdg/autostart/blueman.desktop to /root
Rebooted, blueman applet does not start, rfkill shows hci0 is soft blocked.
```
root@linaro-alip:~# rfkill list bluetooth
1: hci0: Bluetooth
        Soft blocked: yes
        Hard blocked: no
```
The bluetooth daemon is started:
```
root@linaro-alip:/etc# ps aux | grep blue
root      1571  0.0  0.3   4964  3336 ?        Ss   18:55   0:00 /usr/lib/bluetooth/bluetoothd
root      1676  0.0  0.0   4340   584 ttyAMA0  S+   19:30   0:00 grep blue
```

**Comment by docularxu** [comment]
Verified on snapshot 289. Fixed.

**Comment by fboudra** [comment]
confirmed here as well. It was a kernel issue. no changes in the userspace.
